### ISSUE TITLE
`UnderlineSpaces` and `StrikethroughSpaces` don't seem to work properly

### ISSUE THREAD

**Issue by knz** [charmbracelet/lipgloss#113]
We're supposed to be able to use these methods to decide whether spaces are subject to the underline/strikethrough styles.

Unfortunately, this effect is not reached. There's no visible difference in the output.

![Screenshot_2022-09-03_23-07-32](https://user-images.githubusercontent.com/642886/188287688-95dcbf14-bc1b-41ef-b29d-e294a50d5e4e.png)

Found while working on #109.

**Comment by knz** [comment]
cc @muesli @meowgorithm

**Comment by flippedcracker** [comment]
Seeing the same

**Comment by Delta456** [comment]
I investigated this issue and it looks like both `UnderlineSpaces` and `StrikethroughSpaces` don't work because `Underline` will underline the whole string along with the spaces.

More info in the below screenshot and code:

![image](https://github.com/charmbracelet/lipgloss/assets/28479139/e4a8c31d-adb9-4113-9236-48d6340ea0ee)

```go
buttonStyle = lipgloss.NewStyle().
			Foreground(lipgloss.Color("#FFF7DB")).
			Background(lipgloss.Color("#888B7E")).
			Padding(0, 3).
			MarginTop(1)

	activeButtonStyle = buttonStyle.
				Foreground(lipgloss.Color("#FFF7DB")).
				Background(lipgloss.Color("#F25D94")).
				MarginRight(2).
				Underline(true).UnderlineSpaces(false)

```

To solve this one would have to check the flag when writing to the string buffer and skip the spaces when underlining or using strikethrough.
