### ISSUE TITLE
Example for simple table with Borders

### ISSUE THREAD

**Issue by miketonks-form3** [charmbracelet/lipgloss#98]
Really great library and examples, but I am struggling to render a table with borders.

It would be really useful to add an example for this.  Seems like a common use case.

There are a few libraries that do complex interactive table around based on this library, but I'm looking for a really simple way to just render some text in a table, with the ability for additional styling (foreground / background color etc) with lipgloss.

**Comment by miketonks-form3** [comment]
Initial Attempt: https://gist.github.com/miketonks-form3/39fe6a9b171cc1a114d7021400db613c

**Comment by miketonks-form3** [comment]
![image](https://user-images.githubusercontent.com/103417258/182631592-81ae996a-e26c-404d-bc8c-2d91b0c3c6bf.png)

For some reason the bottom and right borders do not render?

**Comment by miketonks-form3** [comment]
Would you welcome a PR for adding this example somewhere, e.g. `/examples/table` ?

**Comment by maaslalani** [comment]
Hey @miketonks-form3, great work! Yes, `./examples/table-bordered` would be a great place!

**Comment by maaslalani** [comment]
Oh, @miketonks-form3 sorry I misunderstood this, I thought you were using the new `table` bubble that we introduced recently https://github.com/charmbracelet/bubbles/tree/master/table.

I'm fairly sure you should be able to use this to print the table and set the table to a `Blurred` state so that it is not interactive.

**Comment by miketonks** [comment]
Thankyou, this looks great 👍
